[2024-11-22T02:34:32.187+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-22T02:34:32.226+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_pipeline.load_weather_data manual__2024-11-22T02:34:10.407768+00:00 [queued]>
[2024-11-22T02:34:32.251+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_pipeline.load_weather_data manual__2024-11-22T02:34:10.407768+00:00 [queued]>
[2024-11-22T02:34:32.253+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-11-22T02:34:32.290+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load_weather_data> on 2024-11-22 02:34:10.407768+00:00
[2024-11-22T02:34:32.307+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=654) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-22T02:34:32.313+0000] {standard_task_runner.py:72} INFO - Started process 656 to run task
[2024-11-22T02:34:32.316+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather_data_pipeline', 'load_weather_data', 'manual__2024-11-22T02:34:10.407768+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmppf1wr0m3']
[2024-11-22T02:34:32.327+0000] {standard_task_runner.py:105} INFO - Job 30: Subtask load_weather_data
[2024-11-22T02:34:32.465+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_data_pipeline.load_weather_data manual__2024-11-22T02:34:10.407768+00:00 [running]> on host a303ff5ff27e
[2024-11-22T02:34:32.726+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_data_pipeline' AIRFLOW_CTX_TASK_ID='load_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-22T02:34:10.407768+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-22T02:34:10.407768+00:00'
[2024-11-22T02:34:32.729+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-22T02:34:32.783+0000] {warnings.py:112} WARNING - /opt/***/dags/etl_pipeline.py:45: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  hourly_data = pd.read_json(hourly_json)

[2024-11-22T02:34:32.824+0000] {warnings.py:112} WARNING - /opt/***/dags/etl_pipeline.py:46: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  daily_data = pd.read_json(daily_json)

[2024-11-22T02:34:32.872+0000] {connection.py:277} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-11-22T02:34:32.877+0000] {base.py:84} INFO - Retrieving connection 'google_cloud_default'
[2024-11-22T02:34:37.143+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-22T02:34:37.172+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-22T02:34:37.173+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=weather_data_pipeline, task_id=load_weather_data, run_id=manual__2024-11-22T02:34:10.407768+00:00, execution_date=20241122T023410, start_date=20241122T023432, end_date=20241122T023437
[2024-11-22T02:34:37.257+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-22T02:34:37.299+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-22T02:34:37.303+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
